name: mmw

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache maven local repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore: |
          ${{ runner.os }}-maven-

    - name: Build with maven
      run: mvn clean install
      working-directory: ./backend

    - name: Run tests
      run: mvn test
      working-directory: ./backend
